#!/usr/bin/env node
/**
 * Solve the two free parameters of the odds engine against the schema's
 * calibration targets, and write them to data/config.json.
 *
 *   slope       how sharply an advantage converts into win rate
 *   difficulty  global offset added to every boss threshold
 *
 * Targets (from the schema):
 *   median 13-0 chance   ~2-8%, aimed at 5%
 *   top 1% of drafts     above 40%, aimed at 45%
 *
 * difficulty moves the median; slope widens the spread between a median draft
 * and a god roll. Both are monotone, so each gets a bisection — difficulty on
 * the inside, slope on the outside.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { load, root, sampleScores, totals, quantile, sampleAdvancedScores } from './lib/sim.mjs';

const TARGET_MEDIAN = 0.05;
const TARGET_P99 = 0.45;
const N_SOLVE = 25_000;

const bosses = load('data/bosses.json');
const { items } = load('data/items.json');

console.log(`calibrate${process.argv.includes('--advanced') ? ' (advanced)' : ''}: ${items.length} items, ${bosses.length} fights, ${N_SOLVE.toLocaleString()} drafts`);

/**
 * Advanced mode reaches the same five axes by a different road — real stat
 * curves instead of assigned ratings — so its spread of drafts is a different
 * distribution and needs its own two parameters. Solving one set for both would
 * put one mode off target.
 */
const advanced = process.argv.includes('--advanced');
const sample = advanced
  ? sampleAdvancedScores(items, bosses, N_SOLVE)
  : sampleScores(items, bosses, N_SOLVE);
const buf = new Float64Array(N_SOLVE);

/** Given a slope, find the difficulty that puts the median exactly on target. */
function solveDifficulty(slope) {
  let lo = -40;
  let hi = 40;
  for (let i = 0; i < 60; i++) {
    const mid = (lo + hi) / 2;
    const median = quantile(totals(sample, bosses, slope, mid, buf), 0.5);
    // Higher difficulty => lower odds, so the comparison is inverted.
    if (median > TARGET_MEDIAN) lo = mid;
    else hi = mid;
  }
  return (lo + hi) / 2;
}

let slopeLo = 0.05;
let slopeHi = 12;
let best = null;

for (let i = 0; i < 40; i++) {
  const slope = (slopeLo + slopeHi) / 2;
  const difficulty = solveDifficulty(slope);
  const t = totals(sample, bosses, slope, difficulty, buf);
  const p99 = quantile(t, 0.99);
  best = { slope, difficulty, p99, median: quantile(t, 0.5) };
  if (p99 < TARGET_P99) slopeLo = slope;
  else slopeHi = slope;
}

const solved = {
  slope: +best.slope.toFixed(4),
  difficulty: +best.difficulty.toFixed(4),
};

// Keep whichever mode is not being solved exactly as it was, so re-solving one
// never silently moves the other.
const existing = load('data/config.json');
const config = advanced
  ? { ...existing, advanced: { ...solved, solvedAt: new Date().toISOString().slice(0, 10) } }
  : {
      ...solved,
      draftSize: 5,
      solvedAt: new Date().toISOString().slice(0, 10),
      targets: { median: TARGET_MEDIAN, p99: TARGET_P99, drafts: N_SOLVE },
      note: 'Generated by tools/calibrate.mjs. Do not hand-edit — rerun the solver. `advanced` holds the same two parameters solved against Advanced mode, via --advanced.',
      advanced: existing.advanced,
    };

writeFileSync(join(root, 'data/config.json'), `${JSON.stringify(config, null, 2)}\n`);

// Print what was actually solved, not what the merged file happens to hold —
// in advanced mode config.slope is still the casual value it preserved.
console.log(`  slope       ${solved.slope}`);
console.log(`  difficulty  ${solved.difficulty}`);
console.log(`  median      ${(best.median * 100).toFixed(2)}%  (target ${TARGET_MEDIAN * 100}%)`);
console.log(`  top 1%      ${(best.p99 * 100).toFixed(2)}%  (target >${TARGET_P99 * 100}%)`);
console.log('  wrote data/config.json');
